import type { Metadata } from "next";
import "../../styles/globalStyles.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MainLayout = ({ children }: { children: any }) => {
  return <main className='page-container'>{children}</main>;
};

export default MainLayout;
