import type { Metadata } from "next";
import HeadSection from "../HeadSection";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MainLayout = ({
  children,
  pageTitle,
}: {
  children: any;
  pageTitle: string;
}) => {
  return (
    <>
      <HeadSection pageTitle={pageTitle} />
      <main className='page-container'>{children}</main>
    </>
  );
};

export default MainLayout;
